INSERT INTO BUILDING(ID,NAME) VALUES (1,'Bat1');
INSERT INTO BUILDING(ID,NAME) VALUES (2,'Bat2');

INSERT INTO ROOM(ID, NAME, FLOOR,BUILDING_ID) VALUES(1, 'Room1', 1,1);
INSERT INTO ROOM(ID, NAME, FLOOR,BUILDING_ID) VALUES(2, 'Room2', 1,2);

INSERT INTO LIGHT(ID,STATUS,BRI,COLOUR,SAT, ROOM_ID) VALUES (1,'ON',1,0,0,1);
INSERT INTO LIGHT(ID,STATUS,BRI,COLOUR,SAT, ROOM_ID) VALUES (2,'OFF',1,0,0,1);